spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://mariadb.c6jwfv2hle7i.ap-northeast-2.rds.amazonaws.com:3306/cocktagorize
        username: admin
        password: admin1234

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                format_sql: true